### ISSUE TITLE
Pola i farmerzy

### ISSUE THREAD

**Issue by mmbednarek** [mmbednarek/msi-carcassonne#12]
Pola są specyficzne ponieważ łączą się narożnikami a nie krawędziami tak jak miasta i drogi.
Należy zrobić nowy rodzaj krawędzi oraz połączeń specjalnie pod pola oraz zaimplementować liczenie miast przyległych
do danej grupy pól.

**Comment by kpmrozowski** [comment]
jeśli jest wolne to to wezmę
